#Range: -12 ~ 12
instrument_pitch = 1
#Allowed Values: KEYBOARD_LAYOUT, NOTE_NAME, DO_RE_MI, ABC_1, ABC_2, NONE
label_type = "KEYBOARD_LAYOUT"
#Allowed Values: MONO, MIXED, STEREO
channel_type = "MIXED"
#Stops all background music when you or someone else within 10.0 blocks of range plays an instrument
stop_music_on_play = true
emit_ring_animation = true
#Defines whether you will see others playing on your instrument's screen
display_other_players = true
render_background = false
accurate_accidentals = true
accepted_genshin_consent = true
#Allowed Values: OLD, NEW
zither_sound_type = "NEW"
#Allowed Values: DON_KA, KEYBOARD_LAYOUT, NONE
drum_label_type = "KEYBOARD_LAYOUT"

