# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				tnt_minecart = true
				chicken = true
				pig = true
				rabbit = true
				glow_squid = true
				zombie = true
				bat = true
				squid = true
				skeleton = true
				spider = true
				creeper = true
				axolotl = true
				chest_minecart = true
				salmon = true
				horse = true
				cow = true
				sheep = true
				villager = true
				iron_golem = true
				cat = true
				dolphin = true
				cod = true
				witch = true
				item = true
				drowned = true
				enderman = true
				turtle = true
				cave_spider = true
				polar_bear = true
				wolf = true
				fox = true
				bee = true
				slime = true
				zombie_villager = true

			[light_sources.settings.entities.naturalist]
				snail = true
				lizard = true
				butterfly = true
				snake = true
				cardinal = true
				bear = true
				deer = true
				duck = true
				bass = true
				coral_snake = true
				robin = true

			[light_sources.settings.entities.lilwings]
				swallow_tail_butterfly = true
				grayling_butterfly = true
				red_applefly_butterfly = true

